[package]
name = "model"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]

[dependencies]
bitflags = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
nalgebra = { version = "0.16", features = ["serde-serialize"] }
nalgebra-glm = "0.2"
noise = "0.5"
